/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ModeloTabla;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import modelo.Cliente;
import controlador.Empresa;
import modelo.Sala;

/**
 *
 * @author ADMINMJ
 */
public class PanelConsulta extends javax.swing.JPanel {
Empresa miEmpresa;
DefaultComboBoxModel modelo;
ModeloTabla modeloTabla;

    /**
     * Creates new form PanelConsulta
     */
    public PanelConsulta(Empresa miEmpresa) {
        initComponents();
        this.miEmpresa=miEmpresa;
        modelo=new DefaultComboBoxModel();
        cmbClientes.setModel(modelo);
        modeloTabla=new ModeloTabla();
        String [] titulo= {"Denominación","Capaciadad"};
        modeloTabla.setColumnIdentifiers(titulo);
        tblSalas.setModel(modeloTabla);
        cargarClientes();
        cargarSalas();
        
    }
    
    
    private void cargarClientes()
    {
        ArrayList<Cliente> clientes=miEmpresa.getClientes();
        for ( int i=0;i< clientes.size();i++)
            // Solamente muestro aquello clientes que tienen salas alquiladas
            if( clientes.get(i).getAlquiladas().size()!=0)
                modelo.addElement(clientes.get(i));
    }
    private void cargarSalas(){
        // Primero elimino las filas que pudieran estar viendose
        // Guardamos en primer lugar el número de filas, ya que cç
        // cada vez que se elimina una se actualiza este valor.
        int filas=modeloTabla.getRowCount();
        for( int fila=0; fila < filas; fila++)
            modeloTabla.removeRow(0);// siempre borramos la fila 0, porque van subiendo
        
        // Obtengo la información del cliente seleccionado.
        Cliente c= (Cliente)modelo.getSelectedItem();
        // compruebo que realmente haya algún cliente seleccionado
        if ( c!=null){
            for ( int i=0; i< c.getAlquiladas().size(); i++){
                Sala s= c.getAlquiladas().get(i);// salas que el cliente tiene alquiladas
                Vector v=new Vector();
                v.add(s.getDenominacion());
                v.add(s.getCapacidad());
                modeloTabla.addRow(v);
                        
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbClientes = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSalas = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("CONSULTA DE SALAS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Cliente");

        cmbClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbClientes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbClientesItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Salas Alquiladas");

        tblSalas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblSalas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(jLabel2)
                                .addGap(40, 40, 40)
                                .addComponent(cmbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(235, 235, 235)
                                .addComponent(jLabel3)))
                        .addGap(0, 31, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbClientesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbClientesItemStateChanged
       //muestro las salas que el cliente tiene alquiladas.
        cargarSalas();
    }//GEN-LAST:event_cmbClientesItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSalas;
    // End of variables declaration//GEN-END:variables
}
