/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import modelo.Empresa;
import modelo.Linea;
import modelo.Parada;

/**
 *
 * @author USUARIO
 */
public class PanelAlta extends javax.swing.JPanel {

    Empresa miEmpresa;

    DefaultComboBoxModel modeloPrimera;
    DefaultComboBoxModel modeloUltima;
    DefaultListModel modeloIntermedio;
    DefaultListModel modeloInterFinal;

    public PanelAlta(Empresa e) {
        initComponents();
        miEmpresa = e;
        modeloPrimera = new DefaultComboBoxModel();
        cmbPrimera.setModel(modeloPrimera);
        modeloUltima = new DefaultComboBoxModel();
        cmbUltima.setModel(modeloUltima);

        modeloIntermedio = new DefaultListModel();
        lstInter.setModel(modeloIntermedio);
        modeloInterFinal = new DefaultListModel();
        lstInterFinal.setModel(modeloInterFinal);
        cargarParadas();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstInter = new javax.swing.JList<>();
        btnAñadir = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstInterFinal = new javax.swing.JList<>();
        btnGrabar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        txtDenominacion = new javax.swing.JTextField();
        cmbPrimera = new javax.swing.JComboBox<>();
        cmbUltima = new javax.swing.JComboBox<>();
        txtFrecuencia = new javax.swing.JTextField();

        jLabel1.setText("Codigo");

        jLabel2.setText("Denominacion");

        jLabel3.setText("Primera_Parada");

        jLabel4.setText("Ultima_Parada");

        jLabel5.setText("Frecuencia");

        jLabel7.setText("PARADAS INTERMEDIAS");

        lstInter.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstInter);

        btnAñadir.setText(">>");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });

        btnQuitar.setText("<<");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        lstInterFinal.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstInterFinal);

        btnGrabar.setText("GRABAR");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnCancelar.setText("CANCELAR");

        cmbPrimera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbUltima.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtFrecuencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFrecuenciaFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtDenominacion)
                    .addComponent(txtFrecuencia, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbUltima, javax.swing.GroupLayout.Alignment.LEADING, 0, 246, Short.MAX_VALUE)
                    .addComponent(cmbPrimera, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnGrabar)
                        .addGap(155, 155, 155))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAñadir)
                            .addComponent(btnQuitar))
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(425, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGrabar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDenominacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnCancelar)
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbPrimera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmbUltima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtFrecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAñadir)
                        .addGap(37, 37, 37)
                        .addComponent(btnQuitar)
                        .addGap(71, 71, 71))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(31, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed

        int pos = lstInter.getSelectedIndex();

        if (pos == -1) {

            JOptionPane.showMessageDialog(this, "No hay Elementos");

        } else {

            Parada p = (Parada) modeloIntermedio.getElementAt(pos);
            modeloIntermedio.remove(pos);
            modeloInterFinal.addElement(p);
        }

    }//GEN-LAST:event_btnAñadirActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed

        int pos = lstInterFinal.getSelectedIndex();

        if (pos == -1) {

            JOptionPane.showMessageDialog(this, "No hay Elementos");

        } else {

            Parada p = (Parada) modeloInterFinal.getElementAt(pos);

            modeloInterFinal.remove(pos);
            modeloIntermedio.addElement(p);

        }
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void txtFrecuenciaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFrecuenciaFocusLost

        String frecuencia = txtFrecuencia.getText();

        try {

            Integer.parseInt(frecuencia);

        } catch (NumberFormatException ex) {

            JOptionPane.showMessageDialog(this, "Deben ser Numeros");
            txtFrecuencia.requestFocus();
            txtFrecuencia.setSelectionStart(0);
            txtFrecuencia.setSelectionEnd(frecuencia.length());

        }
    }//GEN-LAST:event_txtFrecuenciaFocusLost

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed

        int codigo, frecuencia;
        String denominacion;
        Parada primera, ultima;
        ArrayList<Parada> intermedia = new ArrayList();
        Linea l;

        codigo = Integer.parseInt(txtCodigo.getText());
        l = new Linea(codigo);

        if (!miEmpresa.getLineas().contains(l)) {

            denominacion = txtDenominacion.getText();
            frecuencia = Integer.parseInt(txtFrecuencia.getText());
            primera = (Parada) modeloPrimera.getElementAt(cmbPrimera.getSelectedIndex());
            ultima = (Parada) modeloUltima.getElementAt(cmbUltima.getSelectedIndex());
            for (int i = 0; i < modeloInterFinal.size(); i++) {
                intermedia.add((Parada) modeloInterFinal.getElementAt(i));

            }
            l = new Linea(codigo, denominacion, frecuencia, primera, ultima, intermedia);
            miEmpresa.nuevaLinea(l);
            JOptionPane.showMessageDialog(this,"Añadido con exito");
            limpiar();

        } else {

            JOptionPane.showMessageDialog(this, " la linea ya existe");

        }


    }//GEN-LAST:event_btnGrabarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JComboBox<String> cmbPrimera;
    private javax.swing.JComboBox<String> cmbUltima;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstInter;
    private javax.swing.JList<String> lstInterFinal;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDenominacion;
    private javax.swing.JTextField txtFrecuencia;
    // End of variables declaration//GEN-END:variables

    private void cargarParadas() {
        modeloPrimera.removeAllElements();
        modeloUltima.removeAllElements();
        modeloIntermedio.removeAllElements();

        ArrayList<Parada> paradas = miEmpresa.getParadas();
        for (int i = 0; i < paradas.size(); i++) {

            modeloPrimera.addElement(paradas.get(i));
            modeloUltima.addElement(paradas.get(i));
            modeloIntermedio.addElement(paradas.get(i));

        }
    }

    private void cargar() {

        modeloIntermedio.removeAllElements();

        ArrayList<Parada> paradas = miEmpresa.getParadas();
        for (int i = 0; i < paradas.size(); i++) {

            modeloIntermedio.addElement(paradas.get(i));

        }

    }

    private void limpiar() {

        this.txtCodigo.setText("");
        this.txtDenominacion.setText("");
        cmbPrimera.setSelectedIndex(0);
        cmbUltima.setSelectedIndex(0);
        this.txtFrecuencia.setText("");
        cargar();

    }
}
