/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Controlador.Centro;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class Ventana extends javax.swing.JFrame {
    
    Centro miCentro;

    Alta pAlta;
    Alquiler pAlquiler;
    Consulta pConsulta;
    
    
    public Ventana() {
        initComponents();
        setLocation(250,250);
        this.setResizable(false);
        
        //------------------------
         miCentro= new Centro();
         miCentro.grabarSalas();
         
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuAlta = new javax.swing.JMenuItem();
        mnuAlquilar = new javax.swing.JMenuItem();
        mnuConsultar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Gestion_de_Alquileres");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.FlowLayout());

        jMenu1.setText("Menú");

        mnuAlta.setText("AltaUsuario");
        mnuAlta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnuAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAltaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuAlta);

        mnuAlquilar.setText("AlquilarSala");
        mnuAlquilar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnuAlquilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAlquilarActionPerformed(evt);
            }
        });
        jMenu1.add(mnuAlquilar);

        mnuConsultar.setText("ConsultarSala");
        mnuConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultarActionPerformed(evt);
            }
        });
        jMenu1.add(mnuConsultar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       String [] botones={"Cerrar","Cancelar"}; // botones que nos va a  // aparecer en el cuadro de dialogo        
          int eleccion; 
          // para guardar que ha seleccionado el usuario         
          eleccion= JOptionPane.showOptionDialog(this, " ¿ Realmente desea salir", "Cerrar Aplicacion"  , 0,0, null, botones,this);
          // ventana de dialogo , donde preguntamos al usuario que desea hacer 
          
            if ( eleccion==JOptionPane.YES_OPTION){// el usuario ha seleccionado si
                dispose();             
                System.exit(0); 
            }else{ // informos al usuario que ha seleccionado cancelar y no se hace nada.
                JOptionPane.showMessageDialog( this," Proceso de cierre cancelado", "Cerrar Aplicación", JOptionPane.INFORMATION_MESSAGE);     
            }    
    }//GEN-LAST:event_formWindowClosing

    private void mnuAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAltaActionPerformed
        
        eliminarPaneles();   
        
        pAlta= new Alta(miCentro);
        
        getContentPane().add(pAlta);        
        pack();
    }//GEN-LAST:event_mnuAltaActionPerformed

    private void mnuConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultarActionPerformed
        
        // El usuario ha seleccionado la opción de alta        
        //primero eliminamos el panel que se esté mostrando        
        eliminarPaneles();         
        // A continuación instanciamos el panel que queremos mostrar        
        pConsulta=new Consulta(miCentro);         
        // y por último se lo agregamos a nuestra ventana         
        getContentPane().add(pConsulta);        
        pack();
    }//GEN-LAST:event_mnuConsultarActionPerformed

    private void mnuAlquilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAlquilarActionPerformed
         // El usuario ha seleccionado la opción de alta        
        //primero eliminamos el panel que se esté mostrando        
        eliminarPaneles();         
        // A continuación instanciamos el panel que queremos mostrar        
        pAlquiler=new Alquiler(miCentro);         
        // y por último se lo agregamos a nuestra ventana         
        getContentPane().add(pAlquiler);        
        pack();
               
    }//GEN-LAST:event_mnuAlquilarActionPerformed

    private void eliminarPaneles(){     
    try{         
        this.remove(pAlta);     
    } catch(Exception ex){} 
    
    try {         
        this.remove(pAlquiler);     
    }catch(Exception ex){} 
    
    try {         
        this.remove(pConsulta);    
    }catch(Exception ex){} 
} 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuAlquilar;
    private javax.swing.JMenuItem mnuAlta;
    private javax.swing.JMenuItem mnuConsultar;
    // End of variables declaration//GEN-END:variables
}
