/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Empresa;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.Cliente;
import modelo.Sala;

/**
 *
 * @author USUARIO
 */
public class Alquiler extends javax.swing.JPanel {

    Empresa miEmpresa;
    DefaultComboBoxModel modelo;

    public Alquiler(Empresa miEmpresa) {
        initComponents();
        this.miEmpresa = miEmpresa;
        modelo = new DefaultComboBoxModel();
        cargarSalas();
        cmbSalas.setModel(modelo);
        habilitar();

    }

    private void habilitar() {

        if (modelo.getSize() == 0) {

            //No hay ninguna sala disponible
            // deshabilitar botones
            btnAlquilar.setEnabled(false);
            btnCancelar.setEnabled(false);
            txtCif.setEditable(false);
            JOptionPane.showMessageDialog(this, " No hay disponibilidad de salas",
                    "Información", JOptionPane.INFORMATION_MESSAGE);

        }

    }

    private void cargarSalas() {
        //primero limpio el modelo.
        modelo.removeAllElements();
        //recupero las salas que hay en la empresa
        ArrayList<Sala> salas = miEmpresa.getSalas();

        for (int i = 0; i < salas.size(); i++) {

            //compruebo si esta disponible.
            if (!salas.get(i).isOcupada()) {

                modelo.addElement(salas.get(i));
            }

        }

    }

    private void buscarCliente(String cif) {

        Cliente c = miEmpresa.buscarUnCliente(cif);

        if (c != null) {

            lblNombre.setText(c.getNombre());

        } else {

            lblNombre.setText("****************");
        }

    }

    private void limpiar() {
        txtCif.setText("");
        lblNombre.setText("*************");
        cargarSalas();
        habilitar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbSalas = new javax.swing.JComboBox<>();
        txtCif = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        btnAlquilar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Alquilar Salas");

        jLabel2.setText("Salas");

        jLabel3.setText("Cif Cliente");

        cmbSalas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSalas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbSalasKeyPressed(evt);
            }
        });

        txtCif.setBackground(new java.awt.Color(0, 51, 255));
        txtCif.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCifFocusLost(evt);
            }
        });
        txtCif.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCifKeyPressed(evt);
            }
        });

        lblNombre.setText("**************************************");

        btnAlquilar.setText("Alquilar");
        btnAlquilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlquilarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel2)
                .addGap(60, 60, 60)
                .addComponent(cmbSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnAlquilar))
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel3)
                .addGap(66, 66, 66)
                .addComponent(txtCif, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnCancelar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2))
                    .addComponent(btnAlquilar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(cmbSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txtCif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblNombre))
                    .addComponent(btnCancelar)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCifKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCifKeyPressed

        if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
            // Aquí no hace falta llamar a buscarEmpresa , porque pierde
            // el foco al ir al botón Alquilar.
            btnAlquilar.requestFocus();
        } else {
            if (KeyEvent.VK_ESCAPE == evt.getKeyCode()) {
                txtCif.setText("");
            }
        }
    }//GEN-LAST:event_txtCifKeyPressed

    private void txtCifFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCifFocusLost
        buscarCliente(txtCif.getText());
    }//GEN-LAST:event_txtCifFocusLost

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cmbSalasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbSalasKeyPressed

        if (KeyEvent.VK_F1 == evt.getKeyCode()) {

            int posicion = cmbSalas.getSelectedIndex();
            if (posicion != -1) {

                Sala s = (Sala) cmbSalas.getSelectedItem();

                JOptionPane.showMessageDialog(this, s.getDenominacion() + "tiene una capacidad de " + s.getCapacidad() + "Personas",
                        "Informacion", JOptionPane.INFORMATION_MESSAGE);

            }

        }
    }//GEN-LAST:event_cmbSalasKeyPressed

    private void btnAlquilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlquilarActionPerformed
        
        Cliente c= miEmpresa.buscarUnCliente(txtCif.getText());
        
        int posicion= cmbSalas.getSelectedIndex();
        Sala s= (Sala) modelo.getElementAt(posicion);
        
        
        if(c !=null){
        
        
            s.setOcupada(true);
            
            c.guardar(s);
            
            limpiar();
        }else{
        
            JOptionPane.showMessageDialog(this, "El cliente no existe",
                    "Información", JOptionPane.ERROR_MESSAGE);
            lblNombre.setText("********************");
            txtCif.requestFocus();
            txtCif.setSelectionStart(0);
            txtCif.setSelectionEnd(txtCif.getText().length());        
        
        
        }
        
    }//GEN-LAST:event_btnAlquilarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlquilar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cmbSalas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtCif;
    // End of variables declaration//GEN-END:variables
}
