/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Empresa;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class Principal extends javax.swing.JFrame {

   private Empresa miEmpresa;
   private Alquiler pAlquiler;
   private Consulta pConsulta;
   private AltaCliente pAlta;
    
    
    public Principal() {
        miEmpresa = new Empresa();
        initComponents();
         this.setSize(800, 600);
        this.setLocationRelativeTo(null);
       crearSalas();
       
    }

    private void crearSalas(){
    
        miEmpresa.nuevaSala("Sala Nexo", 30);
        miEmpresa.nuevaSala("Sala Barroco", 200);
        miEmpresa.nuevaSala("Sala Gorilas", 1000);
        miEmpresa.nuevaSala("Sala Unicoronio", 300);
    }
    
      private void eliminarPaneles(){
        try{
            remove(pAlta);
        }catch (Exception ex){}
        try{
            remove(pAlquiler);
        }
        catch(Exception ex){}
          try{
            remove(pConsulta);
        }
        catch(Exception ex){}
          try{ 
                pAlta.setVisible(false);
              
          }catch(Exception ex){}
    }
      
      private void cerrar()
      {
          int eleccion;
            
            eleccion= JOptionPane.showConfirmDialog(this,"¿Desea cerrar la vebtana?",
                    "Cerrar Ventana",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            
            if(eleccion== JOptionPane.YES_OPTION){
            
                dispose();
                System.exit(0);
            }
      
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuAlta = new javax.swing.JMenuItem();
        mnuAlquilar = new javax.swing.JMenuItem();
        mnuConsulta = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuFin = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.FlowLayout());

        jMenu1.setText("Operaciones");

        mnuAlta.setText("Alta Clientes");
        mnuAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAltaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuAlta);

        mnuAlquilar.setText("Alquilar Salas");
        mnuAlquilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAlquilarActionPerformed(evt);
            }
        });
        jMenu1.add(mnuAlquilar);

        mnuConsulta.setText("Consulta Ocupacion");
        mnuConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuConsulta);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");

        mnuFin.setText("Fin_de_Aplicación");
        mnuFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFinActionPerformed(evt);
            }
        });
        jMenu2.add(mnuFin);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAltaActionPerformed
        eliminarPaneles();
        pAlta = new AltaCliente(miEmpresa);
        getContentPane().add(pAlta);
        pack();
    }//GEN-LAST:event_mnuAltaActionPerformed

    private void mnuAlquilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAlquilarActionPerformed
        
        eliminarPaneles();
        
        pAlquiler= new Alquiler(miEmpresa);
        getContentPane().add(pAlquiler);
        pack();
    }//GEN-LAST:event_mnuAlquilarActionPerformed

    private void mnuConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultaActionPerformed
        eliminarPaneles();
        
        pConsulta=new Consulta(miEmpresa);
        getContentPane().add(pConsulta);
        pack();
    }//GEN-LAST:event_mnuConsultaActionPerformed

    private void mnuFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFinActionPerformed
        cerrar();
    }//GEN-LAST:event_mnuFinActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrar();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuAlquilar;
    private javax.swing.JMenuItem mnuAlta;
    private javax.swing.JMenuItem mnuConsulta;
    private javax.swing.JMenuItem mnuFin;
    // End of variables declaration//GEN-END:variables
}
