/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Empresa;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Usuario;

/**
 *
 * @author Barbero
 */
public class panelBaja extends javax.swing.JPanel {
    
    Empresa miEmpresa;
    Usuario usuariovalidado;
    DefaultTableModel modelo;

    /**
     * Creates new form panelBaja
     */
    public panelBaja() {
        initComponents();
    }
    
    public panelBaja(Empresa miEmpresa, Usuario usuariovalidado) {
        initComponents();
        this.miEmpresa = miEmpresa;
        this.usuariovalidado = usuariovalidado;
        modelo = new DefaultTableModel();
        String[]titulos = {"USUARIO", "CONTRASEÑA"};
        modelo.setColumnIdentifiers(titulos);
        tblUsuarios.setModel(modelo);
        cargarUsuarios();
    }
    
    private void cargarUsuarios(){
        boolean tengaselementos = true;
        int pos = 0;
        while(tengaselementos && pos < miEmpresa.getUsuarios().size()){
            Vector v = new Vector();
            v.add(miEmpresa.getUsuarios().get(pos).getUsuario());
            v.add(miEmpresa.getUsuarios().get(pos).getContra());
            modelo.addRow(v); //al modelo añadele una fila con lo que tiene v
            //que son los datos de antes
            pos++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();

        jLabel1.setText("BAJA-CONSULTA USUARIO");

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
       int fila = tblUsuarios.rowAtPoint(evt.getPoint());
       String usuario = (String) modelo.getValueAt(fila, 0);
       Usuario n = new Usuario(usuario);
       int pos = miEmpresa.getUsuarios().indexOf(n);
       if(pos != -1){
            int confirmacion = JOptionPane.showConfirmDialog(this, "Esta seguro de borra este usuario", 
                    "ELIMINAR USUARIO", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(confirmacion == 0){
                miEmpresa.getUsuarios().remove(pos);
                modelo.removeRow(pos);
            }
        }
    }//GEN-LAST:event_tblUsuariosMouseClicked
    
    private void actualizarTabla(){
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsuarios;
    // End of variables declaration//GEN-END:variables
}
