/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;
import modelo.Empresa;
import modelo.Usuario;

/**
 *
 * @author USUARIO
 */
public class Administrador extends javax.swing.JFrame {

    
   Usuario usuarioValidado; 
   Empresa miEmpresa;
   PanelAlta pAlta;
   PanelBaja pBaja;
   PanelEnviar pEnviar;
   PanelEntrada pEntrada;
   SudoSuUsuarios alterPassUser;
   AlterPassEstandar alterEstandar;
   
    public Administrador(Empresa e, Usuario usuarioValidado) {
        
          this.miEmpresa=e;
        initComponents();
        this.usuarioValidado=usuarioValidado;
        this.setSize(400, 300);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuUsuarios = new javax.swing.JMenu();
        mnuAlta = new javax.swing.JMenuItem();
        mnuBaja = new javax.swing.JMenuItem();
        mnuCambiarPassUsuarios = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuCambiarMiPass = new javax.swing.JMenuItem();
        mnuMensajes = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        mnuEntrada = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenu();
        mnuDesconectar = new javax.swing.JMenuItem();
        mnuFinAplicacion = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.FlowLayout());

        mnuUsuarios.setText("Usuarios");

        mnuAlta.setText("Alta");
        mnuAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAltaActionPerformed(evt);
            }
        });
        mnuUsuarios.add(mnuAlta);

        mnuBaja.setText("Baja-Consulta");
        mnuBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBajaActionPerformed(evt);
            }
        });
        mnuUsuarios.add(mnuBaja);

        mnuCambiarPassUsuarios.setText("Cambiar_Pass_aUsuarios");
        mnuCambiarPassUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCambiarPassUsuariosActionPerformed(evt);
            }
        });
        mnuUsuarios.add(mnuCambiarPassUsuarios);

        jMenuBar1.add(mnuUsuarios);

        jMenu2.setText("Perfil");

        mnuCambiarMiPass.setText("Cambiar_miPass");
        mnuCambiarMiPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCambiarMiPassActionPerformed(evt);
            }
        });
        jMenu2.add(mnuCambiarMiPass);

        jMenuBar1.add(jMenu2);

        mnuMensajes.setText("Mensajes");

        jMenuItem6.setText("Enviair_Mensaje");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        mnuMensajes.add(jMenuItem6);

        mnuEntrada.setText("Bandeja_Entreda");
        mnuEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEntradaActionPerformed(evt);
            }
        });
        mnuMensajes.add(mnuEntrada);

        jMenuBar1.add(mnuMensajes);

        Salir.setText("Salir");

        mnuDesconectar.setText("Desconectar");
        mnuDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDesconectarActionPerformed(evt);
            }
        });
        Salir.add(mnuDesconectar);

        mnuFinAplicacion.setText("Fin_de_Aplicación");
        mnuFinAplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFinAplicacionActionPerformed(evt);
            }
        });
        Salir.add(mnuFinAplicacion);

        jMenuBar1.add(Salir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAltaActionPerformed
       
        eliminarPaneles();
        pAlta= new PanelAlta(miEmpresa,usuarioValidado);
        getContentPane().add(pAlta);
        pack();
        
    }//GEN-LAST:event_mnuAltaActionPerformed

    private void mnuBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBajaActionPerformed
        
        eliminarPaneles();
        pBaja= new PanelBaja(miEmpresa,usuarioValidado);
        getContentPane().add(pBaja);
        pack();
    }//GEN-LAST:event_mnuBajaActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        
        eliminarPaneles();
        pEnviar=new PanelEnviar(miEmpresa, usuarioValidado);
        getContentPane().add(pEnviar);
        pack();
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void mnuEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEntradaActionPerformed
        
        eliminarPaneles();
        pEntrada= new PanelEntrada(miEmpresa, usuarioValidado);
        getContentPane().add(pEntrada);
        pack();
        
    }//GEN-LAST:event_mnuEntradaActionPerformed

    private void mnuDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDesconectarActionPerformed
        
            new Validacion(miEmpresa).setVisible(true);
            dispose();
            pack();
    }//GEN-LAST:event_mnuDesconectarActionPerformed

    private void mnuFinAplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFinAplicacionActionPerformed
    
            int eleccion;
            
            eleccion= JOptionPane.showConfirmDialog(this,"¿Desea cerrar la vebtana?",
                    "Cerrar Ventana",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            
            if(eleccion== JOptionPane.YES_OPTION){
            
                dispose();
                System.exit(0);
            }
    }//GEN-LAST:event_mnuFinAplicacionActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
            int eleccion;
            
            eleccion= JOptionPane.showConfirmDialog(this,"¿Desea cerrar la vebtana?",
                    "Cerrar Ventana",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            
            if(eleccion== JOptionPane.YES_OPTION){
            
                dispose();
                System.exit(0);
            }
    }//GEN-LAST:event_formWindowClosing

    private void mnuCambiarMiPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCambiarMiPassActionPerformed
     
       eliminarPaneles(); 
       alterEstandar=new AlterPassEstandar(miEmpresa, usuarioValidado);
       getContentPane().add(alterEstandar);
       pack();
        
    }//GEN-LAST:event_mnuCambiarMiPassActionPerformed

    private void mnuCambiarPassUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCambiarPassUsuariosActionPerformed
    
    
        eliminarPaneles();
        alterPassUser= new SudoSuUsuarios(miEmpresa, usuarioValidado);
        getContentPane().add(alterPassUser);
        pack();
        
    }//GEN-LAST:event_mnuCambiarPassUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */

    
    
    private void eliminarPaneles(){
        try{
            getContentPane().remove(alterPassUser);
        }catch(Exception ex){}
        
        try{
            getContentPane().remove(pAlta);
        }catch(Exception ex){}
        
        
        try{
         getContentPane().remove(pBaja);
        }catch(Exception ex){}
        
        
        try{
         getContentPane().remove(pEnviar);
        }catch(Exception ex){}
        
        try{
         getContentPane().remove(pEntrada);
        }catch(Exception ex){}
        
       
        try{
            getContentPane().remove(alterEstandar);
        }catch(Exception ex){}
 
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Salir;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem mnuAlta;
    private javax.swing.JMenuItem mnuBaja;
    private javax.swing.JMenuItem mnuCambiarMiPass;
    private javax.swing.JMenuItem mnuCambiarPassUsuarios;
    private javax.swing.JMenuItem mnuDesconectar;
    private javax.swing.JMenuItem mnuEntrada;
    private javax.swing.JMenuItem mnuFinAplicacion;
    private javax.swing.JMenu mnuMensajes;
    private javax.swing.JMenu mnuUsuarios;
    // End of variables declaration//GEN-END:variables

 


}
