/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.Biblioteca;


public class Principal extends javax.swing.JFrame {

   
    Biblioteca miBiblio;
// Nos tenemos que definir tantas propiedades como paneles distintos vamos a utilizar
    PanelAlta pAlta;
    
    public Principal() {
         initComponents();
        this.setSize(800, 600);// tamaño de la ventana
        this.setResizable(false);// bloquear para que la ventana no se pueda
        // redimensionar.
       // crearLibros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuAlta = new javax.swing.JMenuItem();
        mnuLibros = new javax.swing.JMenuItem();
        mnuPrestamos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jMenu1.setText("Operaciones");

        mnuAlta.setText("Alta_Clientes");
        mnuAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAltaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuAlta);

        mnuLibros.setText("Alquilar_Libros");
        jMenu1.add(mnuLibros);

        mnuPrestamos.setText("Consultar_prestamos");
        jMenu1.add(mnuPrestamos);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAltaActionPerformed
       
       // El usuario ha seleccionado la opción de alta
        //primero eliminamos el panel que se este mostrando
        eliminarPaneles();
        // A continuación instanciamos el panel que queremos mostrar
        pAlta = new PanelAlta(miBiblio);
        // y por ultimo se lo agregamos a nuestra ventana
        getContentPane().add(pAlta);
        pack();
        
    }//GEN-LAST:event_mnuAltaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
        private void eliminarPaneles() {
        try {
            this.remove(pAlta);
        } catch (Exception ex) {
        }
       /* try {
            this.remove(pPrestamo);
        } catch (Exception ex) {
        }
        try {
            this.remove(pConsulta);
        } catch (Exception ex) {
        }*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuAlta;
    private javax.swing.JMenuItem mnuLibros;
    private javax.swing.JMenuItem mnuPrestamos;
    // End of variables declaration//GEN-END:variables
}
