/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import adaptador.ModeloTabla;
import java.util.ArrayList;
import java.util.Vector;
import modelo.Empresa;
import modelo.Noticia;
import modelo.Usuario;

/**
 *
 * @author ADMINMJ
 */
public class PanelConsulta extends javax.swing.JPanel {

    Empresa miEmpresa;
    Usuario usuarioValidado;
   ModeloTabla modelo;

    public PanelConsulta(Empresa miEmpresa, Usuario usuarioValidado) {
        initComponents();
        this.miEmpresa = miEmpresa;
        this.usuarioValidado = usuarioValidado;
        lblUsuario.setText(usuarioValidado.getNombre());
        modelo=new ModeloTabla();
     /*   Vector titulos=new Vector();
        titulos.add("TÍTULO");
        titulos.add("AUTOR");
       modelo.setColumnIdentifiers(titulos);*/
      String [] titulos={"TÍTULO","AUTOR"};
      modelo.setColumnIdentifiers(titulos);
      tblNoticia.setModel(modelo);
      cargarNoticias();
        
    }
    private void cargarNoticias(){
        ArrayList<Noticia> noticias=miEmpresa.getNoticias();
        for( int pos=0; pos <noticias.size();pos++){
            Vector v=new Vector();
            v.add(noticias.get(pos).getTitulo());
            v.add(noticias.get(pos).getUsuario().getNombre());
            modelo.addRow(v);
                       
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblNoticia = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();

        tblNoticia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNoticia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNoticiaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNoticia);

        jLabel1.setText("TÍTULO");

        txtTitulo.setEditable(false);

        jLabel2.setText("FECHA");

        txtFecha.setEditable(false);

        lblUsuario.setText("jLabel3");

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel3.setText("CATEGORIA");

        txtCategoria.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTitulo)
                            .addComponent(txtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                            .addComponent(txtCategoria))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                        .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(182, 182, 182))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(btnEliminar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblUsuario)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(btnEliminar)
                .addContainerGap(76, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblNoticiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNoticiaMouseClicked
     int fila=tblNoticia.rowAtPoint(evt.getPoint());
     int columna= tblNoticia.columnAtPoint(evt.getPoint());
     String titulo= (String)modelo.getValueAt(fila, columna);
     Noticia n= new Noticia(titulo);
     int pos=miEmpresa.getNoticias().indexOf(n);
     if(pos!=-1)
     {
         txtFecha.setText(miEmpresa.getNoticias().get(pos).getFecha());
         txtCategoria.setText(miEmpresa.getNoticias().get(pos).getCategoria().getDenominacion());
         txtTitulo.setText(titulo);
         if(miEmpresa.getNoticias().get(pos).getUsuario()==usuarioValidado)
         {
             btnEliminar.setEnabled(true);
         }
         else
         {
             btnEliminar.setEnabled(false);
         }
         
     }
    }//GEN-LAST:event_tblNoticiaMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       int fila= tblNoticia.getSelectedRow();
       String titulo= txtTitulo.getText().toString();
     Noticia n= new Noticia(titulo);
     int pos=miEmpresa.getNoticias().indexOf(n);
     miEmpresa.getNoticias().remove(pos);
     modelo.removeRow(fila);
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTable tblNoticia;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
