/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.Categoria;
import modelo.Empresa;
import modelo.Noticia;
import modelo.Usuario;

/**
 *
 * @author ADMINMJ
 */
public class PanelAlta extends javax.swing.JPanel {

    Empresa miEmpresa;
    Usuario usuarioValidado;
    DefaultComboBoxModel modelo;

    /**
     * Creates new form PanelAlta
     */
    public PanelAlta(Empresa miEmpresa, Usuario usuario) {
        initComponents();
        this.miEmpresa = miEmpresa;
        usuarioValidado = usuario;
        // iNSTANCIO UN OBJETO DE TIPO DefaultComboBOxModel
        modelo = new DefaultComboBoxModel();
        // ASIGNO ESE MODELO AL OBJETO DE TIPO JCOMBO
        cmbCategoria.setModel(modelo);
        // CARGAR LOS DATOS A MOSTRAR EN ESE JCOMBO
        cargarCategoria();
        //MUESTRO EL NOBMRE DEL USUARIO EN EL JLABEL
        lblUsuario.setText(usuarioValidado.getNombre());

    }

    private void cargarCategoria() {
        
        modelo.addElement("Seleccione una categoria");
        ArrayList<Categoria> categorias = miEmpresa.getCategorias();
        for (int i = 0; i < categorias.size(); i++) {
            modelo.addElement(categorias.get(i));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbCategoria = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        btnGrabar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("Categoria");

        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("Fecha");

        txtFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFechaKeyPressed(evt);
            }
        });

        txtTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTituloKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("Titulo");

        lblUsuario.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 0, 51));
        lblUsuario.setText("jLabel4");

        btnGrabar.setText("GRABAR");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTitulo)
                    .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbCategoria, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(btnGrabar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(47, 47, 47))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUsuario)
                .addGap(145, 145, 145))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(42, 42, 42)
                .addComponent(btnCancelar)
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGrabar)
                .addGap(56, 56, 56))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        String titulo, fecha;
        Noticia noticia;
        Categoria categoria;
        int pos = cmbCategoria.getSelectedIndex();
        titulo = txtTitulo.getText();
        fecha = txtFecha.getText();
// COMBPROBAR QUE EL USUARIO HAYA SELECCIONADO UNA CATEGORIA
        if (pos == 0) {
// EL USUARIO NO HA SELECCIONADO CATEGORIA, POR LO QUE SE EMITE UN MENSAJE DE ERROR.
            JOptionPane.showMessageDialog(this, " Debe de seleccionar una categoria primero",
                    "Error", JOptionPane.ERROR_MESSAGE);
            cmbCategoria.requestFocus();
        } else {
            categoria = (Categoria) modelo.getElementAt(pos);
            // COMPROBAMOS QUE HA INTRODUCIDO INFORMACIÓN EN TODOS LOS CAMPOS REQUERIDOS
            if (comprobarBlancos(titulo)) {
                JOptionPane.showMessageDialog(this, "Campo requerido",
                        "Error", JOptionPane.ERROR_MESSAGE);
                txtTitulo.setText("");
                txtTitulo.requestFocus();
            } else {
                if (comprobarBlancos(fecha)) {
                    JOptionPane.showMessageDialog(this, "Campo requerido",
                            "Error", JOptionPane.ERROR_MESSAGE);
                    txtFecha.setText("");
                    txtFecha.requestFocus();
                } else {
                    // CREAMOS LA NOTICIA
                    noticia = new Noticia(titulo, categoria, usuarioValidado, fecha);
                    if (miEmpresa.nuevaNoticia(noticia)) {
                        // EL METODO NUEVANOTICA DE LA CLASE EMPRESA DEVUELVE TRUE CUANDO LA NOTICIA YA EXISTE
                        JOptionPane.showMessageDialog(this, "Ya existe una noticia con ese titulo",
                                "Error", JOptionPane.ERROR_MESSAGE);
                        txtTitulo.requestFocus();
                        txtTitulo.setSelectionStart(0);
                        txtTitulo.setSelectionEnd(txtTitulo.getText().length());
                    } else {
                        JOptionPane.showMessageDialog(this, "Nueva noticia incorporada",
                                "correcto", JOptionPane.INFORMATION_MESSAGE);
                        limpiar();
                    }
                }
            }

        }
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtFechaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaKeyPressed
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ENTER:
                txtTitulo.requestFocus();
                break;
            case KeyEvent.VK_ESCAPE:
                txtFecha.setText("");
                
        }
    }//GEN-LAST:event_txtFechaKeyPressed

    private void txtTituloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTituloKeyPressed
      
         switch(evt.getKeyCode()){
            case KeyEvent.VK_ENTER:
                btnGrabar.requestFocus();
                break;
            case KeyEvent.VK_ESCAPE:
                txtTitulo.setText("");
                
        }
    }//GEN-LAST:event_txtTituloKeyPressed
    private void limpiar() {
        txtTitulo.setText("");
        txtFecha.setText("");
        cmbCategoria.setSelectedIndex(0);
    }

    private boolean comprobarBlancos(String texto) {
        /*boolean resultado=false;
    if(texto.trim().equals(""))
        resultado=true;
    return resultado*/

        return texto.trim().equals("") ? true : false;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
