/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import modelo.Empresa;
import modelo.Linea;
import modelo.Parada;

/**
 *
 * @author ADMINMJ
 */
public class PanelAlta extends javax.swing.JPanel {
    
    DefaultComboBoxModel modeloPrimera;
    DefaultComboBoxModel modeloUltima;
    DefaultListModel modeloIntermedio;
    DefaultListModel modeloInterFinal;
    Empresa miEmpresa;

    /**
     * Creates new form PanelAlta
     */
    public PanelAlta(Empresa miEmpresa) {
        initComponents();
        this.miEmpresa = miEmpresa;
        modeloPrimera = new DefaultComboBoxModel();
        cmbPrimera.setModel(modeloPrimera);
        modeloUltima = new DefaultComboBoxModel();
        cmbUltima.setModel(modeloPrimera);
        modeloIntermedio = new DefaultListModel();
        lstInter.setModel(modeloIntermedio);
        modeloInterFinal = new DefaultListModel();
        lstInterFinal.setModel(modeloInterFinal);
        cargarParadas();
    }
    
    private void cargarParadas() {
        modeloPrimera.removeAllElements();
        modeloUltima.removeAllElements();
        modeloIntermedio.removeAllElements();
        ArrayList<Parada> paradas = miEmpresa.getParadas();
        for (int i = 0; i < paradas.size(); i++) {
            modeloPrimera.addElement(paradas.get(i));
            modeloUltima.addElement(paradas.get(i));
            modeloIntermedio.addElement(paradas.get(i));
        }
    }
    private void cargar()
    {
        modeloIntermedio.removeAllElements();
        ArrayList<Parada> paradas = miEmpresa.getParadas();
        for (int i = 0; i < paradas.size(); i++) {
           
            modeloIntermedio.addElement(paradas.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDeno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbPrimera = new javax.swing.JComboBox<>();
        cmbUltima = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtFrecuencia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstInter = new javax.swing.JList<>();
        btnAnadir = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstInterFinal = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        btnNueva = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        jLabel1.setText("CODIGO");

        jLabel2.setText("DENOMINACIÓN");

        jLabel3.setText("Primera Parada");

        jLabel4.setText("Ultima Parada");

        cmbPrimera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbUltima.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Frecuencia");

        txtFrecuencia.setText("0");
        txtFrecuencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFrecuenciaFocusLost(evt);
            }
        });

        lstInter.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstInter.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstInter);

        btnAnadir.setText(">>");
        btnAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirActionPerformed(evt);
            }
        });

        btnQuitar.setText("<<");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        lstInterFinal.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstInterFinal);

        jLabel6.setText("PARADAS INTERMEDIAS");

        btnNueva.setText("GRABAR LINEA");
        btnNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaActionPerformed(evt);
            }
        });

        btnCancelar.setText("CANCELAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbUltima, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCodigo)
                            .addComponent(cmbPrimera, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDeno, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 25, Short.MAX_VALUE))
                            .addComponent(txtFrecuencia)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAnadir)
                            .addComponent(btnQuitar))
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar)
                    .addComponent(btnNueva))
                .addGap(209, 209, 209))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAnadir)
                        .addGap(28, 28, 28)
                        .addComponent(btnQuitar)
                        .addGap(103, 103, 103))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btnNueva)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtDeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(cmbPrimera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(cmbUltima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(txtFrecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(13, 13, 13)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(btnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(60, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirActionPerformed
        int posicion = lstInter.getSelectedIndex();
        if (posicion == -1) {
            JOptionPane.showMessageDialog(this, "error");
        } else {
            Parada p = (Parada) modeloIntermedio.getElementAt(posicion);
            modeloIntermedio.remove(posicion);
            modeloInterFinal.addElement(p);
        }
        
    }//GEN-LAST:event_btnAnadirActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        int posicion = lstInterFinal.getSelectedIndex();
        if (posicion == -1) {
            JOptionPane.showMessageDialog(this, "error");
        } else {
            Parada p = (Parada) modeloInterFinal.getElementAt(posicion);
            modeloInterFinal.remove(posicion);
            modeloIntermedio.addElement(p);
        }
        
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void txtFrecuenciaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFrecuenciaFocusLost
        String frecuencia = txtFrecuencia.getText();
     
        
        try {
            Integer.parseInt(frecuencia);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, " la frecuencia debe ser numérica");
            txtFrecuencia.requestFocus();
            txtFrecuencia.setSelectionStart(0);
            txtFrecuencia.setSelectionEnd(frecuencia.length());
        }
    }//GEN-LAST:event_txtFrecuenciaFocusLost

    private void btnNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaActionPerformed
     int codigo,frecuencia;
     String denominacion;
     Parada primera, ultima;
     ArrayList<Parada> intermedia=new ArrayList<>();
     Linea l;
      codigo= Integer.parseInt( txtCodigo.getText());
      l=new Linea(codigo);
      if (!miEmpresa.getLineas().contains(l))
      {
          denominacion=txtDeno.getText();
          frecuencia=Integer.parseInt(txtFrecuencia.getText());
          primera=(Parada)modeloPrimera.getElementAt(cmbPrimera.getSelectedIndex());
          ultima=(Parada)modeloUltima.getElementAt(cmbUltima.getSelectedIndex());
          for ( int i=0;i<modeloInterFinal.size(); i++){
              intermedia.add((Parada)modeloInterFinal.getElementAt(i));
          }
          l=new Linea(codigo,denominacion,frecuencia,primera,ultima,intermedia);
          miEmpresa.anadirLinea(l);
          limpiar();
          
      }
      else{
          JOptionPane.showMessageDialog(this, " la linea ya existe");
      }
      
    }//GEN-LAST:event_btnNuevaActionPerformed
private void limpiar(){
    txtCodigo.setText("");
    txtDeno.setText("");
    cmbPrimera.setSelectedIndex(0);
    cmbUltima.setSelectedIndex(0);
    modeloInterFinal.clear();
    cargar();
    
    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadir;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnNueva;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JComboBox<String> cmbPrimera;
    private javax.swing.JComboBox<String> cmbUltima;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstInter;
    private javax.swing.JList<String> lstInterFinal;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDeno;
    private javax.swing.JTextField txtFrecuencia;
    // End of variables declaration//GEN-END:variables
}
