/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.sun.glass.events.KeyEvent;
import controlador.Empresa;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.Cliente;
import modelo.Sala;

/**
 *
 * @author USUARIO
 */
public class PanelAlquiler extends javax.swing.JPanel {
    
    Empresa miEmpresa;
    DefaultComboBoxModel modelo;

    /**
     * Creates new form PanelAltaCliente
     */
    public PanelAlquiler(Empresa empresa) {
        
        initComponents();
        miEmpresa = empresa;
        modelo = new DefaultComboBoxModel();
        cargarSalas();
        cmbSalas.setModel(modelo);
        habilitar();
        
        this.setSize(700, 500);
    }
    
    public void habilitar(){
    
        if(modelo.getSize()==0){
        
            //desactibo los botones si el modelo esta vacio
        btnAlquilar.setEnabled(false);
        btnCancelar.setEnabled(false);
        txtCif.setEnabled(false);
        
        }
    
    
    
    }
    
    public void cargarSalas() {
        
        modelo.removeAllElements();//primero vacio el modelo
        
        ArrayList<Sala> salas = miEmpresa.getSala();// guardo las salas que ttien la empresa en el ArrayList salas
        
        for (int i = 0; i < salas.size(); i++) {

            // pregunto si esa sala esta ocupada
            if (!salas.get(i).isOcupada()) {
                
                modelo.addElement(salas.get(i));
                
            }
            
        }
    }
    
    private void buscarCliente(String cif) {
        
        Cliente c = miEmpresa.buscarUnCliente(cif);
        
        if (c != null) {
            
            lblnombre.setText(c.getNombre());
            
        } else {
            
            lblnombre.setText("*****************");
        }
        
    }
    
        private void limpiar() {
        txtCif.setText("");
        lblnombre.setText("*************");
        cargarSalas();
        habilitar();
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbSalas = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtCif = new javax.swing.JTextField();
        lblnombre = new javax.swing.JLabel();
        btnAlquilar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Arial", 2, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Alquiler de Salas");

        jLabel2.setText("Sala");

        cmbSalas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSalas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbSalasKeyPressed(evt);
            }
        });

        jLabel3.setText("CIF");

        txtCif.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCifFocusLost(evt);
            }
        });
        txtCif.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCifKeyPressed(evt);
            }
        });

        lblnombre.setText("**************************");

        btnAlquilar.setText("Alquilar");
        btnAlquilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlquilarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel3)))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCif, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCancelar)
                                    .addComponent(lblnombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btnAlquilar)))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbSalas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblnombre)))
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlquilar)
                    .addComponent(btnCancelar))
                .addContainerGap(111, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlquilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlquilarActionPerformed
        
        Cliente c = miEmpresa.buscarUnCliente(txtCif.getText());// primero busca un cliente
        
        Sala s= (Sala)cmbSalas.getSelectedItem();
                
                if(c !=null){//preguntamos si existe el cliente
                
                s.setOcupada(true);//declaramos que esta ocupada la sala
                
                c.añadirSala(s);// y por ultimo agregamos la sala al cliente
                
                limpiar();
                
                }else{
                
                                JOptionPane.showMessageDialog(this, "El cliente no existe",
                    "Información", JOptionPane.ERROR_MESSAGE);
            lblnombre.setText("********************");
            txtCif.requestFocus();
            txtCif.setSelectionStart(0);
            txtCif.setSelectionEnd(txtCif.getText().length());
 
                
                }

        
    }//GEN-LAST:event_btnAlquilarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        
        limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cmbSalasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbSalasKeyPressed
        
        
        if(KeyEvent.VK_F1== evt.getKeyCode()){
        
            int posicion= cmbSalas.getSelectedIndex();
            
            if (posicion != -1) {
                Sala s = (Sala) cmbSalas.getSelectedItem();

                JOptionPane.showMessageDialog(this, s.getNombre() + " tiene una capacidad de " + s.getCapacidad() + " personas",
                        "Información ", JOptionPane.INFORMATION_MESSAGE);
            }
            
        
        
        
        }
    }//GEN-LAST:event_cmbSalasKeyPressed

    private void txtCifKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCifKeyPressed
        if (java.awt.event.KeyEvent.VK_ENTER == evt.getKeyCode()) {
            // Aquí no hace falta llamar a buscarEmpresa , porque pierde
            // el foco al ir al botón Alquilar.
            btnAlquilar.requestFocus();
        } else {
            if (java.awt.event.KeyEvent.VK_ESCAPE == evt.getKeyCode()) {
                txtCif.setText("");
            } 
    }//GEN-LAST:event_txtCifKeyPressed
    }
    private void txtCifFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCifFocusLost
          buscarCliente(txtCif.getText());
    }//GEN-LAST:event_txtCifFocusLost
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlquilar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cmbSalas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JTextField txtCif;
    // End of variables declaration//GEN-END:variables
}
