/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Empresa;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class Pincipal extends javax.swing.JFrame {

    Empresa miEmpresa;

    PanelAlta pAlta;
    PanelAlquiler pAlquilar;
    PanelConsulta pConsulta;

    public Pincipal() {
        initComponents();
        miEmpresa = new Empresa();
        crearSalas();
        this.setSize(700, 500);
        setLocationRelativeTo(null);
    }
    
    
    
    public void crearSalas(){
    
    miEmpresa.nuevaSala("Sala Prometeo", 100);
    miEmpresa.nuevaSala("Sala Omega", 50);
    miEmpresa.nuevaSala("Sala Afrodita", 260);
    miEmpresa.nuevaSala("Sala Zeus", 450);
    miEmpresa.nuevaSala("Sala Mitos",3000);
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuAltaUsuario = new javax.swing.JMenuItem();
        mnuAlquilarSala = new javax.swing.JMenuItem();
        mnuConsulta = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuFin = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.FlowLayout());

        jMenu1.setText("Operaciones");

        mnuAltaUsuario.setText("Alta_Usuario");
        mnuAltaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAltaUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(mnuAltaUsuario);

        mnuAlquilarSala.setText("Alquilar_Sala");
        mnuAlquilarSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAlquilarSalaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuAlquilarSala);

        mnuConsulta.setText("Consulta_Prestamo");
        mnuConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuConsulta);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");

        mnuFin.setText("Fin_de_App");
        mnuFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFinActionPerformed(evt);
            }
        });
        jMenu2.add(mnuFin);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAltaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAltaUsuarioActionPerformed
        eliminarPaneles();

        pAlta = new PanelAlta(miEmpresa);
        this.getContentPane().add(pAlta);
        pack();


    }//GEN-LAST:event_mnuAltaUsuarioActionPerformed

    private void mnuAlquilarSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAlquilarSalaActionPerformed
        eliminarPaneles();

        pAlquilar = new PanelAlquiler(miEmpresa);
        this.getContentPane().add(pAlquilar);
        pack();
    }//GEN-LAST:event_mnuAlquilarSalaActionPerformed

    private void mnuConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultaActionPerformed
        eliminarPaneles();

        pConsulta = new PanelConsulta(miEmpresa);
        this.getContentPane().add(pConsulta);
        pack();
    }//GEN-LAST:event_mnuConsultaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrar();
    }//GEN-LAST:event_formWindowClosing

    private void mnuFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFinActionPerformed
        cerrar();
    }//GEN-LAST:event_mnuFinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pincipal().setVisible(true);
            }
        });
    }

    public void eliminarPaneles() {

        try {
            remove(pAlta);

        } catch (Exception ex) {

        }
        try {

            remove(pAlquilar);
        } catch (Exception ex) {

        }
        try {

            remove(pConsulta);

        } catch (Exception ex) {

        }

    }
    
        private void cerrar()
    {
      int eleccion;
        eleccion=JOptionPane.showConfirmDialog(this, " ¿ Desea realmente cerrar la ventana",
                " Cerrar Ventana", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if ( eleccion==JOptionPane.YES_OPTION)
        {
            dispose();
            System.exit(0);
        }  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem mnuAlquilarSala;
    private javax.swing.JMenuItem mnuAltaUsuario;
    private javax.swing.JMenuItem mnuConsulta;
    private javax.swing.JMenuItem mnuFin;
    // End of variables declaration//GEN-END:variables
}
