/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import modelo.Biblioteca;

/**
 *
 * @author USUARIO
 */
public class PanelAlta extends javax.swing.JPanel {

    Biblioteca miBiblio;
    
    
    
    public PanelAlta(Biblioteca miBiblio) {
        initComponents();
        this.miBiblio=miBiblio;
    }
    
    
    
    public boolean validarCampo(JTextField texto){
    
       boolean resultado;
       
       resultado= texto.getText().trim().isEmpty();
    
       if(resultado){
       
           JOptionPane.showMessageDialog(this, " Campo Requerido", " Validación ", JOptionPane.ERROR_MESSAGE);
            texto.requestFocus();
    
       }
       
     return resultado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtLogin = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtPass = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AltaUsuarios");

        jLabel2.setText("Nombre_Apellidos");

        jLabel3.setText("Login");

        jLabel4.setText("Pass");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });

        txtLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLoginKeyPressed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(151, 151, 151)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                    .addComponent(txtPass)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(btnGuardar)
                        .addGap(108, 108, 108)
                        .addComponent(btnCancelar)))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addGap(92, 92, 92))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
       
        switch(evt.getKeyCode()){
        
            case KeyEvent.VK_ENTER:
                txtLogin.requestFocus();
                break;
            
            case KeyEvent.VK_ESCAPE:
                 txtNombre.setText("");
                break;
                
            case KeyEvent.VK_F1:
                
                JOptionPane.showMessageDialog(this,"Falta Nombre Usuario","Informacion",JOptionPane.INFORMATION_MESSAGE);
                break;
        }
        
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoginKeyPressed
        
        switch(evt.getKeyCode()){
        
            case KeyEvent.VK_ENTER:
                txtPass.requestFocus();
                break;
            
            case KeyEvent.VK_ESCAPE:
                txtLogin.setText("");
                break;
            
            case KeyEvent.VK_F1:
                
                JOptionPane.showMessageDialog(this,"Falta  LOGIN ","Informacion",JOptionPane.INFORMATION_MESSAGE);
                break;        
        }
    }//GEN-LAST:event_txtLoginKeyPressed

    private void txtPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyPressed
        
               switch(evt.getKeyCode()){
        
            case KeyEvent.VK_ENTER:
                btnGuardar.requestFocus();
                break;
            
            case KeyEvent.VK_ESCAPE:
                txtPass.setText("");
                break;
            
            case KeyEvent.VK_F1:
                
                JOptionPane.showMessageDialog(this,"Falta Contraseña ","Informacion",JOptionPane.INFORMATION_MESSAGE);
                break;        
        } 
               
               
       
    }//GEN-LAST:event_txtPassKeyPressed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       
        String nombre, login, pass;
        
        int resultado;
        
        if(!validarCampo(txtNombre) && !validarCampo(txtLogin) && !validarCampo(txtPass)){
        
        
            nombre= txtNombre.getText();
            login= txtLogin.getText();
            pass= txtPass.getText();
            
            resultado = miBiblio.nuevoUsuario(nombre, login, pass);
            
            if(resultado==-1){
            
            JOptionPane.showMessageDialog(this,"Usuario Añadido","Informacion",JOptionPane.INFORMATION_MESSAGE);
            
            
            }else{
            
            
                 JOptionPane.showMessageDialog(this, "Ya existe un cliente con ese nombre",
                        "Alta", JOptionPane.ERROR_MESSAGE);
                 
                  txtNombre.requestFocus();
                // selecciono el texto introducido
                txtNombre.setSelectionStart(0);// comienzo de la selección
                txtNombre.setSelectionEnd(txtNombre.getText().length());
            
            }
        
        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void limpiar(){
    
    
        txtNombre.setText("");
        txtLogin.setText("");
        txtPass.setText("");
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPass;
    // End of variables declaration//GEN-END:variables
}
