/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ModeloTabla;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.Biblioteca;
import modelo.Libro;
import modelo.Usuario;

public class PanelConsulta extends javax.swing.JPanel {

    Biblioteca miBiblio;
    DefaultComboBoxModel modelo;
    ModeloTabla modeloLibros;

    public PanelConsulta(Biblioteca miBiblio) {
        initComponents();
        this.miBiblio = miBiblio;
        modeloLibros = new ModeloTabla();
        String[] titulo = {"ISBN", "TITULO", "AUTOR", "EDITORIAL"};
        
        modeloLibros.setColumnIdentifiers(titulo);
        tblPrestados.setModel(modeloLibros);
        
        modelo= new DefaultComboBoxModel();
        cargarUsuarios();
        cmbClientes.setModel(modelo);
        
        cmbClientes.setSelectedIndex(0);
        
   

    }

    public void cargarUsuarios() {

        ArrayList<Usuario> usuarios = miBiblio.getUsuarios();

        for (int pos = 0; pos < usuarios.size(); pos++) {

            if (!usuarios.get(pos).getPrestados().isEmpty()) {

                modelo.addElement(usuarios.get(pos));

            }

        }

    }
    
    public void limpiarFilas(){
    
    int fila= modeloLibros.getRowCount();
    
    for(int pos=0; pos<fila; pos++){
    
        modeloLibros.removeRow(0);
    
    }
    
    
    
    
    }
    
    
    
    public void cargarLibrosUsuario(int posicion){
        
        Usuario u= (Usuario)modelo.getElementAt(posicion);
        ArrayList<Libro> libros= u.getPrestados();
        
        Vector v;
        
        for(int i=0; i<libros.size();i++){
        
        v=new Vector();
        
        v.add(libros.get(i).getIsbn());
        v.add(libros.get(i).getTitulo());
        v.add(libros.get(i).getAutor());
        v.add(libros.get(i).getEditorial());
        
        modeloLibros.addRow(v);
        
        }
        
        
    
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrestados = new javax.swing.JTable();
        cmbClientes = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Consulta de Prestamos");

        jLabel2.setText("CLIENTE");

        jLabel3.setText("LIBROS PRESTADOS");

        tblPrestados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPrestados);

        cmbClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(cmbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(cmbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClientesActionPerformed

        int pos= cmbClientes.getSelectedIndex();
        
        if(pos==-1){
        
            JOptionPane.showMessageDialog(this,"PRIMERO SELECCIONA UN USUARIO","JOPUTA",JOptionPane.ERROR_MESSAGE);
        
        }else{
        
        
            limpiarFilas();
            
            cargarLibrosUsuario(pos);
        
        
        }
        
    }//GEN-LAST:event_cmbClientesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPrestados;
    // End of variables declaration//GEN-END:variables
}
