/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ModeloTabla;
import java.util.ArrayList;
import java.util.Vector;
import modelo.Empresa;
import modelo.Noticia;
import modelo.Usuario;

/**
 *
 * @author USUARIO
 */
public class PanelConsulta extends javax.swing.JPanel {

    Empresa miEmpresa;
    Usuario usuarioValidado;
    ModeloTabla modelo;
    
    /**
     * Creates new form PanelConsulta
     */
    public PanelConsulta(Empresa e ,Usuario usuarioValidado) {
        initComponents();
        miEmpresa = e;
        this.usuarioValidado=usuarioValidado;
        lblUsuario.setText(usuarioValidado.getNombre());
        modelo = new ModeloTabla();
       /* 
        Vector titulos= new Vector();
        titulos.add("Titulo");
        titulos.add("Autor");
       
        modelo.setColumnIdentifiers(titulos);
        */
       
       String [] titulos ={"Titulo", "Autor"};
       modelo.setColumnIdentifiers(titulos);
       tblNoticia.setModel(modelo);
       cargarNoticias();
    }
    
    private void cargarNoticias(){
    
        ArrayList<Noticia> noticias=miEmpresa.getNoticias();
        
        for (int i = 0; i< noticias.size(); i++){
        
            Vector v = new Vector();
            
            v.add(noticias.get(i).getTitulo());
            v.add(noticias.get(i).getUsuario().getNombre());
            
            modelo.addRow(v);
        
        
        }
    
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblNoticia = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTiulo = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();

        tblNoticia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblNoticia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNoticiaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNoticia);

        jLabel1.setText("Titulo");

        jLabel2.setText("Fecha");

        lblUsuario.setText("Usuario");

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(txtTiulo)
                    .addComponent(txtFecha)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(lblUsuario)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblUsuario)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTiulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(btnEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblNoticiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNoticiaMouseClicked
        
        int fila = tblNoticia.rowAtPoint(evt.getPoint());
        int columna= tblNoticia.columnAtPoint(evt.getPoint());
       
        String  titulo=(String) modelo.getValueAt(fila, columna);
        Noticia n=new Noticia(titulo);
        int pos= miEmpresa.getNoticias().indexOf(n);
        
        if(pos != -1){
        
        txtTiulo.setText(titulo);
        txtFecha.setText(miEmpresa.getNoticias().get(pos).getFecha());
        if(miEmpresa.getNoticias().get(pos).getUsuario()== usuarioValidado){
        
        
                btnEliminar.setEnabled(true);
        }else{
        
        
                btnEliminar.setEnabled(false);
        
        }
        
        
        
        }
    }//GEN-LAST:event_tblNoticiaMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        int fila = tblNoticia.getSelectedRow();
        
       String  titulo=(String) txtTiulo.getText().toString();
        Noticia n=new Noticia(titulo);
        int pos= miEmpresa.getNoticias().indexOf(n);
        miEmpresa.getNoticias().remove(pos);
        modelo.removeRow(fila);
        limpiar();
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTable tblNoticia;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtTiulo;
    // End of variables declaration//GEN-END:variables
}
