/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import controlador.Empresa;

/**
 *
 * @author ADMINMJ
 */
public class Principal extends javax.swing.JFrame {

    private Empresa miEmpresa;
    private PanelAltaCliente pAlta;
    private PanelAlquiler pAlquiler;
    private PanelConsulta pConsulta;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        centrarVentana();
        miEmpresa=new Empresa();
        crearSalas();
    }
private void crearSalas()
{
    miEmpresa.nuevaSala("Sala Burgos", 30);
    miEmpresa.nuevaSala(" Salar Fiesta", 200);
    miEmpresa.nuevaSala( " Sala Esperanza", 400);
    miEmpresa.nuevaSala( " Sala Final", 50);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuAltaClientes = new javax.swing.JMenuItem();
        mnuAlquiler = new javax.swing.JMenuItem();
        mnuConsulta = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Gestión de Alquileres");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.FlowLayout());

        jMenu1.setText("Operaciones");

        mnuAltaClientes.setText("Alta Clientes");
        mnuAltaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAltaClientesActionPerformed(evt);
            }
        });
        jMenu1.add(mnuAltaClientes);

        mnuAlquiler.setText("Alquilar Salas");
        mnuAlquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAlquilerActionPerformed(evt);
            }
        });
        jMenu1.add(mnuAlquiler);

        mnuConsulta.setText("Consulta Ocupación");
        mnuConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuConsulta);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");

        mnuSalir.setText("Fin de la Aplicación");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        jMenu2.add(mnuSalir);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
       cerrar();
        
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       cerrar();
    }//GEN-LAST:event_formWindowClosing

    private void mnuAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAlquilerActionPerformed
        // llamamos a este método para eliminar el panel que actualmente se está mostrando.
        eliminarPaneles();
        pAlquiler=new PanelAlquiler(miEmpresa);
        this.getContentPane().add(pAlquiler);
        pack();
        
    }//GEN-LAST:event_mnuAlquilerActionPerformed

    private void mnuConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultaActionPerformed
       eliminarPaneles();
       pConsulta=new PanelConsulta(miEmpresa);
       this.getContentPane().add(pConsulta);
       pack();
        
    }//GEN-LAST:event_mnuConsultaActionPerformed

    private void mnuAltaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAltaClientesActionPerformed
      eliminarPaneles();
      pAlta=new PanelAltaCliente(miEmpresa);
      getContentPane().add(pAlta).setVisible(true);
      pack();
    }//GEN-LAST:event_mnuAltaClientesActionPerformed

    private void eliminarPaneles(){
        try{
            remove(pAlta);
        }catch (Exception ex){}
        try{
            remove(pAlquiler);
        }
        catch(Exception ex){}
          try{
            remove(pConsulta);
        }
        catch(Exception ex){}
    }
    private void cerrar()
    {
      int eleccion;
        eleccion=JOptionPane.showConfirmDialog(this, " ¿ Desea realmente cerrar la ventana",
                " Cerrar Ventana", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if ( eleccion==JOptionPane.YES_OPTION)
        {
            dispose();
            System.exit(0);
        }  
    }
    /**
     * Método utilizado para centrar la ventana y cambiar el tamaño.
     */
    private void centrarVentana() {
      Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
      int height = pantalla.height;
      int width = pantalla.width;
      setSize(width/2, height/2);		

      setLocationRelativeTo(null);		
      setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuAlquiler;
    private javax.swing.JMenuItem mnuAltaClientes;
    private javax.swing.JMenuItem mnuConsulta;
    private javax.swing.JMenuItem mnuSalir;
    // End of variables declaration//GEN-END:variables

    
}
