/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Empresa;
import controlador.ModeloTabla;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import modelo.Cliente;
import modelo.Sala;

/**
 *
 * @author USUARIO
 */
public class PanelConsulta extends javax.swing.JPanel {

 Empresa miEmpresa;
DefaultComboBoxModel modelo;
ModeloTabla modeloTabla;

    
    /**
     * Creates new form PanelConsulta
     */
    public PanelConsulta(Empresa miEmpresa) {
        initComponents();
        initComponents();
        this.miEmpresa=miEmpresa;
        modelo=new DefaultComboBoxModel();
        cmbConsulta.setModel(modelo);
        modeloTabla=new ModeloTabla();
        String [] titulo= {"Denominación","Capaciadad"};
        modeloTabla.setColumnIdentifiers(titulo);
        tblConsulta.setModel(modeloTabla);
        cargarClientes();
        cargarSalas();
        
        
    }
    
     private void cargarClientes()
    {
        ArrayList<Cliente> clientes=miEmpresa.getClientes();
        for ( int i=0;i< clientes.size();i++)
            // Solamente muestro aquello clientes que tienen salas alquiladas
            if( clientes.get(i).getAlquiladas().size()!=0)
                modelo.addElement(clientes.get(i));
    }
    private void cargarSalas(){
        // Primero elimino las filas que pudieran estar viendose
        // Guardamos en primer lugar el número de filas, ya que cç
        // cada vez que se elimina una se actualiza este valor.
        int filas=modeloTabla.getRowCount();
        for( int fila=0; fila < filas; fila++)
            modeloTabla.removeRow(0);// siempre borramos la fila 0, porque van subiendo
        
        // Obtengo la información del cliente seleccionado.
        Cliente c= (Cliente)modelo.getSelectedItem();
        // compruebo que realmente haya algún cliente seleccionado
        if ( c!=null){
            for ( int i=0; i< c.getAlquiladas().size(); i++){
                Sala s= c.getAlquiladas().get(i);// salas que el cliente tiene alquiladas
                Vector v=new Vector();
                v.add(s.getDenominacion());
                v.add(s.getCapacidad());
                modeloTabla.addRow(v);
                        
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Salas = new javax.swing.JLabel();
        lblAlquiladas = new javax.swing.JLabel();
        cmbConsulta = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConsulta = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Consulta de Salas");

        Salas.setText("lblSala");

        lblAlquiladas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlquiladas.setText("Salas Alquiladas");

        cmbConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbConsulta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbConsultaItemStateChanged(evt);
            }
        });

        tblConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblConsulta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(290, 290, 290)
                                .addComponent(cmbConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(Salas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 147, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(lblAlquiladas, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salas)
                    .addComponent(cmbConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(lblAlquiladas)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbConsultaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbConsultaItemStateChanged
          cargarSalas();
    }//GEN-LAST:event_cmbConsultaItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Salas;
    private javax.swing.JComboBox<String> cmbConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAlquiladas;
    private javax.swing.JTable tblConsulta;
    // End of variables declaration//GEN-END:variables
}
