/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Empresa;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.Cliente;
import modelo.Sala;

/**
 *
 * @author USUARIO
 */
public class PanelAlquiler extends javax.swing.JPanel {

    Empresa miEmpresa;
    DefaultComboBoxModel modelo;

    
    public PanelAlquiler(Empresa miEmpresa) {
        initComponents();
        this.miEmpresa = miEmpresa;
        modelo = new DefaultComboBoxModel();
        cargarSalas();
        // Asigno al jcombo el modelo.
        cmbSalas.setModel(modelo);
        // compruebo si tengo salas libres
        habilitar();

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblSala = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAlquilar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cmbSalas = new javax.swing.JComboBox<>();
        txtCif = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AQUILAR SALAS");

        lblSala.setText("SALA");

        jLabel3.setText("CLIENTE");

        btnAlquilar.setText("Alquilar");

        btnCancelar.setText("Cancelar");
        btnCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCancelarKeyPressed(evt);
            }
        });

        cmbSalas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSalas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbSalasKeyPressed(evt);
            }
        });

        txtCif.setBackground(new java.awt.Color(0, 51, 204));
        txtCif.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCifFocusLost(evt);
            }
        });
        txtCif.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCifKeyPressed(evt);
            }
        });

        lblNombre.setText("*******************************");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSala)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCif, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(cmbSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAlquilar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(139, 139, 139))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(211, 211, 211))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSala)
                    .addComponent(cmbSalas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlquilar))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar)
                    .addComponent(lblNombre))
                .addContainerGap(273, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSalasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbSalasKeyPressed

           if (KeyEvent.VK_F1 == evt.getKeyCode()) {
            int posicion = cmbSalas.getSelectedIndex();
            if (posicion != -1) {
                Sala s = (Sala) cmbSalas.getSelectedItem();

                JOptionPane.showMessageDialog(this, s.getDenominacion() + " tiene una capacidad de " + s.getCapacidad() + " personas",
                        "Información ", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        


        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSalasKeyPressed

    private void txtCifKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCifKeyPressed

        if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
            // Aquí no hace falta llamar a buscarEmpresa , porque pierde
            // el foco al ir al botón Alquilar.
            btnAlquilar.requestFocus();
        } else {
            if (KeyEvent.VK_ESCAPE == evt.getKeyCode()) {
                txtCif.setText("");
            }
        }
        
        
    }//GEN-LAST:event_txtCifKeyPressed

    private void txtCifFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCifFocusLost
     
        buscarCliente(txtCif.getText());
    }//GEN-LAST:event_txtCifFocusLost

    private void btnCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCancelarKeyPressed
     
                limpiar();

    }//GEN-LAST:event_btnCancelarKeyPressed


      private void limpiar() {
        txtCif.setText("");
        lblNombre.setText("*************");
        cargarSalas();
        habilitar();
    }
      
          private void buscarCliente(String cif) {
        Cliente c = miEmpresa.buscarUnCliente(cif);
        if (c != null) {
            lblNombre.setText(c.getNombre());
        } else {
            lblNombre.setText("***************");
        }
    }
    
       private void cargarSalas() {
        // Primero limpio el modelo.
        modelo.removeAllElements();
        // Recupero las salas que hay en la empresa
        ArrayList<Sala> salas = miEmpresa.getSalas();
        for (int i = 0; i < salas.size(); i++) {
            // compruebo si esta disponible.
            if (!salas.get(i).isOcupado()) {
                modelo.addElement(salas.get(i));
            }
        }
    }
       

          private void habilitar() {

        if (modelo.getSize() == 0) {
            //No hay ninguna sala disponible
            // deshabilitar botones
            btnAlquilar.setEnabled(false);
            btnCancelar.setEnabled(false);
            txtCif.setEditable(false);
            JOptionPane.showMessageDialog(this, " No hay disponibilidad de salas",
                    "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlquilar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cmbSalas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSala;
    private javax.swing.JTextField txtCif;
    // End of variables declaration//GEN-END:variables
}
