/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Empresa;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class Principal extends javax.swing.JFrame {
    
    private Empresa miEmpresa;
    private PanelAltaCliente pAlta;
    private PanelAlquiler pAlquiler;
    private PanelConsulta pConsulta;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
        centrarVentana();
        miEmpresa=new Empresa();
        crearSalas();

        
    }
    
    private void crearSalas()
    {
        miEmpresa.nuevaSala("Sala Burgos", 30);
        miEmpresa.nuevaSala("Sala Fiesta", 200);
        miEmpresa.nuevaSala("Sala Esperanza", 400);
        miEmpresa.nuevaSala("Sala Final", 50);
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuOperaciones = new javax.swing.JMenu();
        mnuAlta = new javax.swing.JMenuItem();
        mnuAlquilar = new javax.swing.JMenuItem();
        mnuConsulta = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuFinalizarAplicacion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Gestion de Alquiler");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.FlowLayout());

        mnuOperaciones.setText("Operaciones");

        mnuAlta.setText("Alta_Cliente");
        mnuAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAltaActionPerformed(evt);
            }
        });
        mnuOperaciones.add(mnuAlta);

        mnuAlquilar.setText("Alquilar_Salas");
        mnuAlquilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAlquilarActionPerformed(evt);
            }
        });
        mnuOperaciones.add(mnuAlquilar);

        mnuConsulta.setText("Consulta_Operacion");
        mnuConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultaActionPerformed(evt);
            }
        });
        mnuOperaciones.add(mnuConsulta);

        jMenuBar1.add(mnuOperaciones);

        jMenu2.setText("Salir");

        mnuFinalizarAplicacion.setText("Finalizar_Aplicacion");
        mnuFinalizarAplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFinalizarAplicacionActionPerformed(evt);
            }
        });
        jMenu2.add(mnuFinalizarAplicacion);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuFinalizarAplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFinalizarAplicacionActionPerformed
        
        cerrar();
        
        
    }//GEN-LAST:event_mnuFinalizarAplicacionActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
        cerrar();
    }//GEN-LAST:event_formWindowClosing

    private void mnuAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAltaActionPerformed
    
      eliminarPaneles();
      pAlta=new PanelAltaCliente(miEmpresa);
      getContentPane().add(pAlta).setVisible(true);
      pack();
        
    }//GEN-LAST:event_mnuAltaActionPerformed

    private void mnuAlquilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAlquilarActionPerformed
    
         // llamamos a este método para eliminar el panel que actualmente se está mostrando.
        eliminarPaneles();
        pAlquiler=new PanelAlquiler(miEmpresa);
        this.getContentPane().add(pAlquiler);
        pack();
        
  
    }//GEN-LAST:event_mnuAlquilarActionPerformed

    private void mnuConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultaActionPerformed
        
      
       eliminarPaneles();
       pConsulta=new PanelConsulta(miEmpresa);
       this.getContentPane().add(pConsulta);
       pack();
    }//GEN-LAST:event_mnuConsultaActionPerformed

    public void cerrar(){
    
        int eleccion;
        
        //Estudiar este metodo********
        eleccion= JOptionPane.showConfirmDialog(this, "¿Desea realmente cerrar la Ventana",
                "Cerrar la aplicaccion", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
    
        if(eleccion==JOptionPane.YES_NO_OPTION){
        
            dispose();
            System.exit(0);

        }
    
    }
    
        private void eliminarPaneles(){
        try{
            remove(pAlta);
        }catch (Exception ex){}
        try{
            remove(pAlquiler);
        }
        catch(Exception ex){}
          try{
            remove(pConsulta);
        }
        catch(Exception ex){}
    }
        
    private void centrarVentana() {
      Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
      int height = pantalla.height;
      int width = pantalla.width;
      setSize(width/2, height/2);		

      setLocationRelativeTo(null);		
      setVisible(true);
    }
        
        
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuAlquilar;
    private javax.swing.JMenuItem mnuAlta;
    private javax.swing.JMenuItem mnuConsulta;
    private javax.swing.JMenuItem mnuFinalizarAplicacion;
    private javax.swing.JMenu mnuOperaciones;
    // End of variables declaration//GEN-END:variables
}
