/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Biblioteca;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class Principal extends javax.swing.JFrame {

   
     Biblioteca miBiblio;
     
     //tengo que instanciar los paneles con los que voy a trabajar
     Alta pAlta;
     Alquilar pAlquilar;
     Consulta pConsulta;
    
    public Principal() {
        miBiblio = new Biblioteca();
        initComponents();
        this.setSize(800, 600);
        this.setLocationRelativeTo(null);
        setVisible(true);
        crearLibros();
    }

   /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
       private void crearLibros() {
        miBiblio.nuevoLibro("1234", "Programación1", "Pepe Martínez", "Vicens-vives");
        miBiblio.nuevoLibro("1234", "Entornos de Desarrollo", "María Pardo", "Edelvives");
        miBiblio.nuevoLibro("1234", "Lenguaje de Marcas", "Fernando Alcarrz", "SM");
        miBiblio.nuevoLibro("1234", "Sistemas Informáticos", "Paco Ureña", "Paraninfo");
        miBiblio.nuevoLibro("1234", "Bases de Datos", "Guillermo Delgado", "Mc-Graw HIll");
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jmnuOperaciones = new javax.swing.JMenu();
        jmnuAlta = new javax.swing.JMenuItem();
        jmnuAlquiler = new javax.swing.JMenuItem();
        jmnuConsulta = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.FlowLayout());

        jmnuOperaciones.setText("Operaciones");

        jmnuAlta.setText("AltaUsuarios");
        jmnuAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuAltaActionPerformed(evt);
            }
        });
        jmnuOperaciones.add(jmnuAlta);

        jmnuAlquiler.setText("AlquilarLibros");
        jmnuAlquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuAlquilerActionPerformed(evt);
            }
        });
        jmnuOperaciones.add(jmnuAlquiler);

        jmnuConsulta.setText("ConsultaAlquiler");
        jmnuConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuConsultaActionPerformed(evt);
            }
        });
        jmnuOperaciones.add(jmnuConsulta);

        jMenuBar1.add(jmnuOperaciones);

        jMenu2.setText("Salir");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    
               String[] botones = {"Cerrar", "Cancelar"};
        int eleccion;
        eleccion = JOptionPane.showOptionDialog(this, " ¿ Realmente desea salir", "Cerrar Aplicacion",
                 0, 0, null, botones, this);
        if (eleccion == JOptionPane.YES_OPTION) {
            dispose();
            System.exit(0);

        } else {
            JOptionPane.showMessageDialog(this, " Proceso de cierre cancelado", "Cerrar Aplicación", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jmnuConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuConsultaActionPerformed
        
        eliminarPaneles();
        
        pConsulta= new Consulta(miBiblio);
        getContentPane().add(pConsulta);
        pack();
        
    }//GEN-LAST:event_jmnuConsultaActionPerformed

    private void jmnuAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuAltaActionPerformed
        /*
        El usuario ha seleccionado la opcion de alta
        por lo tanto se quitan los demas paneles primero
        para ello tengo un metodo
        */
        
        eliminarPaneles();
        //de esta manera intancio el panel que quiero agregar
        pAlta= new Alta(miBiblio);
        getContentPane().add(pAlta);
        pack();
    }//GEN-LAST:event_jmnuAltaActionPerformed

    private void jmnuAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuAlquilerActionPerformed
        eliminarPaneles();
        
        pAlquilar = new Alquilar(miBiblio);
        getContentPane().add(pAlquilar);
        pack();
    }//GEN-LAST:event_jmnuAlquilerActionPerformed

      private void eliminarPaneles() {
        try {
            this.remove(pAlta);
        } catch (Exception ex) {
        }
        try {
            this.remove(pAlquilar);
        } catch (Exception ex) {
        }
        try {
            this.remove(pConsulta);
        } catch (Exception ex) {
        }
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmnuAlquiler;
    private javax.swing.JMenuItem jmnuAlta;
    private javax.swing.JMenuItem jmnuConsulta;
    private javax.swing.JMenu jmnuOperaciones;
    // End of variables declaration//GEN-END:variables
}
