/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import modelo.Biblioteca;
import static sun.security.jgss.GSSUtil.login;

/**
 *
 * @author USUARIO
 */
public class PanelAlta extends javax.swing.JPanel {

    public PanelAlta() {

        CabezarAltaUsuarios = new JLabel();
        txtNombre = new JTextField();
        txtLogin = new JTextField();
        txtPasw = new JTextField();
        btnGrabar = new JButton();
      

    }

    PanelAlta(Biblioteca miBiblio) {

        initComponents();

        setVisible(true);
        setSize(800, 600);

    }

    private boolean validarCampo(String valor) {
        boolean resultado = false;
        if (valor.equals("")) {
            resultado = true;
        }
        return resultado;
    }
    

     
     
     
     
 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CabezarAltaUsuarios = new javax.swing.JLabel();
        altaNombre = new javax.swing.JLabel();
        altaLogin = new javax.swing.JLabel();
        altaContraseña = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtLogin = new javax.swing.JTextField();
        txtPasw = new javax.swing.JTextField();
        btnGrabar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));

        CabezarAltaUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        CabezarAltaUsuarios.setFont(new java.awt.Font("Ebrima", 3, 36)); // NOI18N
        CabezarAltaUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CabezarAltaUsuarios.setText("Alta de Usuarios");
        CabezarAltaUsuarios.setToolTipText("");

        altaNombre.setText("Nombre_Apellidos:");

        altaLogin.setText("Login:");

        altaContraseña.setText("Contraseña:");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });

        txtLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLoginKeyPressed(evt);
            }
        });

        txtPasw.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPasw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPaswKeyPressed(evt);
            }
        });

        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(altaContraseña, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGrabar, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(316, 316, 316))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(altaLogin)
                            .addComponent(altaNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                        .addComponent(txtPasw))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnCancelar))
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(286, 286, 286))
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(CabezarAltaUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(CabezarAltaUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(altaNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(altaLogin)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(altaContraseña)
                    .addComponent(txtPasw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGrabar)
                    .addComponent(btnCancelar))
                .addContainerGap(176, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_F1:
                // el usuario ha presionado la tecla F1, por lo que debe             
                // mostrar que información hay que introducir en ese campo.              
                JOptionPane.showMessageDialog(this, " Nombre del usuario", "Información del campo", JOptionPane.INFORMATION_MESSAGE);
                break;
            case KeyEvent.VK_ENTER:
                // el usuario ha presionado la tecla enter
                txtLogin.requestFocus();// coloca el cursor en el siguiente campo
                break;
            case KeyEvent.VK_ESCAPE:
                // el usuario ha presionado escape                
                txtNombre.setText(""); // borrar lo que hay en ese campo.
        }

    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoginKeyPressed

        switch (evt.getKeyCode()) {
            case KeyEvent.VK_F1:
                // el usuario ha presionado la tecla F1, por lo que debe             
                // mostrar que información hay que introducir en ese campo.              
                JOptionPane.showMessageDialog(this, "Login del usuario", "Información del campo", JOptionPane.INFORMATION_MESSAGE);
                break;
            case KeyEvent.VK_ENTER:
                // el usuario ha presionado la tecla enter
                txtPasw.requestFocus();// coloca el cursor en el siguiente campo
                break;
            case KeyEvent.VK_ESCAPE:
                // el usuario ha presionado escape                
                txtLogin.setText(""); // borrar lo que hay en ese campo. 
        }
    }//GEN-LAST:event_txtLoginKeyPressed

    private void txtPaswKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaswKeyPressed

        switch (evt.getKeyCode()) {
            case KeyEvent.VK_F1:
                // el usuario ha presionado la tecla F1, por lo que debe             
                // mostrar que información hay que introducir en ese campo.              
                JOptionPane.showMessageDialog(this, "*Password*", "Información del campo", JOptionPane.INFORMATION_MESSAGE);
                break;
            case KeyEvent.VK_ENTER:
                // el usuario ha presionado la tecla enter
                btnGrabar.requestFocus();// coloca el cursor en el siguiente campo
                break;
            case KeyEvent.VK_ESCAPE:
                // el usuario ha presionado escape                
                txtPasw.setText(""); // borrar lo que hay en ese campo. 
        }
    }//GEN-LAST:event_txtPaswKeyPressed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
      
        
        String nombre = "";
        String login = "";
        String pass = "";

        if (validarCampo(nombre)) { // EL CAMPO ESTA VACÍO POR LO QUE SE ABRE UN VENTANA DE DIALOGO 
            //Y A CONTINUACIÓN COLOCAMOS EL CURSOR EN EL CAMPO REQUERIDO. 

            JOptionPane.showMessageDialog(this, " Campo Requerido 1", " Información", JOptionPane.ERROR_MESSAGE);
            txtNombre.requestFocus();
        } else {
            login = txtLogin.getText().trim();

            if (validarCampo(login)) {
                JOptionPane.showMessageDialog(this, " Campo Requerido 2", " Información", JOptionPane.ERROR_MESSAGE);
                txtLogin.requestFocus();
            } else {
                pass = txtPasw.getText().trim();
            }

            if (validarCampo(pass)) {
                JOptionPane.showMessageDialog(this, " Campo Requerido 3", " Información", JOptionPane.ERROR_MESSAGE);
                txtLogin.requestFocus();
            
            }
            
                
        }
        
        
        
    }//GEN-LAST:event_btnGrabarActionPerformed
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CabezarAltaUsuarios;
    private javax.swing.JLabel altaContraseña;
    private javax.swing.JLabel altaLogin;
    private javax.swing.JLabel altaNombre;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPasw;
    // End of variables declaration//GEN-END:variables
}
